"""DeterministicCodeGenerator's HTML-template Jinja Environment had no
autoescape configured at all -- found 11 Sep 2026 while triaging the
raw-html-escaping gate. entity_list.html.j2 (and its siblings) interpolate
ent.name_display / ent.name_plural / field.display_name -- architect-authored
labels from the solution design UI, with no length or character
restriction -- directly with `{{ }}`, no `|escape` filter, relying entirely
on the Environment's own autoescape setting.

This means every app generated by the platform shipped with a stored XSS in
its own admin UI: an entity or field named with an HTML/script payload would
execute for anyone who ran the generated app and viewed that list page.

Fixed by scoping autoescape to only the *.html.j2 templates in that shared
Environment (it also renders Go/Python/YAML/shell templates for the SAME
generated app, where HTML-escaping '<'/'>' would corrupt the generated
source -- a blanket autoescape=True was not an option).
"""

from app.modules.solutions_product.services.deterministic_code_generator import (
    DeterministicCodeGenerator,
)

MALICIOUS = '<script>alert(1)</script>'


def test_entity_list_template_escapes_architect_authored_labels():
    gen = DeterministicCodeGenerator(language="go-chi")
    tpl = gen._env.get_template("ui/entity_list.html.j2")

    ent = {
        "name_snake": "widget",
        "name_display": MALICIOUS,
        "name_plural": MALICIOUS,
        "fields": [
            {"name": "title", "display_name": MALICIOUS, "is_auto": False},
        ],
    }
    html = tpl.render(ent=ent)

    assert MALICIOUS not in html, "the architect-authored label executed as script in the generated app"
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html


def test_compose_shell_html_escapes_project_name():
    """_compose_shell_html builds the SPA shell with a raw Python f-string
    (not Jinja) -- autoescape doesn't apply here at all, so it needs its own
    explicit html.escape() call, which was missing until this fix."""
    html_out = DeterministicCodeGenerator._compose_shell_html(
        MALICIOUS, 1, "code_123", "", "", "", ""
    )
    assert MALICIOUS not in html_out
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html_out


def test_build_nav_html_escapes_label():
    """nav['label'] is architect-authored (ent.name_plural / wf.name_display),
    unlike nav['path'] which is already sanitized via _snake()."""
    nav_html = DeterministicCodeGenerator._build_nav_html([
        {"type": "entity", "path": "widgets", "label": MALICIOUS},
    ])
    assert MALICIOUS not in nav_html
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in nav_html


def test_non_html_templates_are_not_autoescaped():
    """The same Environment renders Go source -- autoescape must NOT apply
    there, or generated code containing '<'/'>' (e.g. Go generics, comparison
    operators) would be corrupted."""
    gen = DeterministicCodeGenerator(language="go-chi")
    assert callable(gen._env.autoescape)
    assert gen._env.autoescape("main.go.j2") is False
    assert gen._env.autoescape("ui/entity_list.html.j2") is True


def _nextjs_files(solution_name):
    from types import SimpleNamespace

    bundle = SimpleNamespace(
        solution_name=solution_name, solution_id=0, entities=[], services=[],
        workflows=[], relationships=[], confirmed_fields={}, state_machines={},
        identity_provider={}, genome=None,
    )
    gen = DeterministicCodeGenerator(language="python-fastapi")
    return {f.path: f.content for f in gen._generate_nextjs_frontend(bundle)}


def test_nextjs_admin_preview_escapes_solution_name():
    """The Next.js frontend's standalone admin preview (frontend/admin.html)
    is HTML, rendered by an Environment that had autoescape off, so a
    solution name carrying markup ran as script in the generated app."""
    files = _nextjs_files(MALICIOUS)
    html = files["frontend/admin.html"]
    assert MALICIOUS not in html
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html


def test_nextjs_code_templates_are_not_escaped():
    """The same Environment renders TSX; escaping must not touch it."""
    files = _nextjs_files("Plain Name")
    tsx = [c for p, c in files.items() if p.endswith(".tsx")]
    assert tsx, "the Next.js frontend produced no TSX files"
    assert any("<div" in c for c in tsx)
    assert not any("&lt;div" in c for c in tsx)
