"""
FastAPI stub generator — deterministic code generation from ArchiMate elements.

Reads ApplicationComponent and DataObject elements linked to a solution and
produces a runnable FastAPI scaffold using Python string.Template (no Jinja2,
no LLM, fully reproducible).

Public API:
    generate(solution_id) -> dict[str, str]   # {filename: content}
"""

import io
import logging
import re
import textwrap
import zipfile
from string import Template

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Template strings (Python string.Template uses $var / ${var} syntax)
# ---------------------------------------------------------------------------

_ROUTER_T = Template(
    textwrap.dedent("""\
    \"\"\"
    FastAPI router for ${title} — deterministic scaffold.
    Replace the 501 stubs with real implementations.
    \"\"\"
    from fastapi import APIRouter, HTTPException, status
    from typing import Any, List

    router = APIRouter(prefix="/${slug}", tags=["${title}"])


    @router.get("/", response_model=List[Any], summary="List ${title}")
    async def list_${fn}():
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="${title}: list not yet implemented",
        )


    @router.get("/{item_id}", response_model=Any, summary="Get ${title}")
    async def get_${fn}(item_id: int):
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="${title}: get not yet implemented",
        )


    @router.post("/", response_model=Any, status_code=status.HTTP_201_CREATED,
                 summary="Create ${title}")
    async def create_${fn}(body: Any):
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="${title}: create not yet implemented",
        )


    @router.put("/{item_id}", response_model=Any, summary="Update ${title}")
    async def update_${fn}(item_id: int, body: Any):
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="${title}: update not yet implemented",
        )


    @router.delete("/{item_id}", status_code=status.HTTP_204_NO_CONTENT,
                   summary="Delete ${title}")
    async def delete_${fn}(item_id: int):
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="${title}: delete not yet implemented",
        )
    """)
)

_MODEL_T = Template(
    textwrap.dedent("""\
    \"\"\"
    Pydantic model for ${title} — deterministic scaffold.
    \"\"\"
    from __future__ import annotations

    from typing import Any, Optional
    from pydantic import BaseModel


    class ${cls}(BaseModel):
        id: Optional[int] = None
        name: Optional[str] = None
        # TODO: add typed fields from your data dictionary

        class Config:
            from_attributes = True


    class ${cls}Create(BaseModel):
        name: str
        # TODO: required fields for creation


    class ${cls}Update(BaseModel):
        name: Optional[str] = None
        # TODO: optional fields for partial update
    """)
)

_MAIN_T = Template(
    textwrap.dedent("""\
    \"\"\"
    FastAPI application entry-point — auto-generated by Entelim
    Solution: ${solution_id}
    Components: ${component_list}
    \"\"\"
    from fastapi import FastAPI

    ${imports}

    app = FastAPI(
        title="Entelim Generated API — Solution ${solution_id}",
        version="0.1.0",
    )

    ${includes}

    @app.get("/health")
    async def health():
        return {"status": "ok"}
    """)
)

_DOCKER_COMPOSE_T = Template(
    textwrap.dedent("""\
    version: "3.9"

    services:
    ${services}
    """)
)

_DOCKER_SERVICE_T = Template(
    textwrap.dedent("""\
      ${slug}:
        build: .
        environment:
          - SERVICE_NAME=${slug}
        ports:
          - "${port}:8000"
        restart: unless-stopped
    """)
)

_README_T = Template(
    textwrap.dedent("""\
    # Entelim Generated FastAPI Scaffold

    **Solution ID:** ${solution_id}  
    **Generated:** ${timestamp}

    ## Components

    ${components_table}

    ## Quick Start

    ```bash
    # Start all services
    docker compose up --build

    # Or run locally
    pip install fastapi uvicorn
    uvicorn main:app --reload
    ```

    ## Structure

    ```
    main.py                     # Application entry-point
    routers/                    # One router per ApplicationComponent
    ${router_tree}
    models/                     # One Pydantic model per DataObject
    ${model_tree}
    docker-compose.yml          # One service per ApplicationComponent
    ```

    ## Stubs

    Every endpoint currently raises `HTTP 501 Not Implemented`.
    Replace each stub with your business logic.
    """)
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(name: str) -> str:
    """Convert a name to a lowercase underscore-separated identifier."""
    slug = re.sub(r"[^a-z0-9]+", "_", (name or "component").lower()).strip("_")
    return slug or "component"


def _to_class_name(name: str) -> str:
    """Convert a name to PascalCase."""
    return "".join(
        word.capitalize()
        for word in re.split(r"[^a-z0-9]+", (name or "Component").lower())
        if word
    ) or "Component"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate(solution_id: int) -> dict:
    """Generate a deterministic FastAPI scaffold for *solution_id*.

    Queries the database for ApplicationComponent and DataObject ArchiMate
    elements linked to the solution, then renders each file using Python
    string.Template (no Jinja2, no LLM, reproducible).

    Returns
    -------
    dict[str, str]
        Mapping of *filename* → *file content* for all generated files.
        Always includes ``main.py``, ``docker-compose.yml``, and ``README.md``.
    """
    components = _load_components(solution_id)
    data_objects = _load_data_objects(solution_id)

    if not components:
        # Emit a minimal scaffold even with no components so callers always
        # receive a valid (if empty) bundle.
        components = [{"name": "DefaultService", "slug": "default_service"}]

    return _render(solution_id, components, data_objects)


# ---------------------------------------------------------------------------
# DB loading helpers
# ---------------------------------------------------------------------------

def _load_components(solution_id: int) -> list:
    """Return a list of {name, slug} dicts for application-layer elements."""
    try:
        from app.models.solution_archimate_element import SolutionArchiMateElement

        rows = SolutionArchiMateElement.query.filter_by(
            solution_id=solution_id,
            layer_type="application",
        ).all()

        seen_slugs: set = set()
        components = []
        for row in rows:
            name = (row.element_name or "").strip() or f"Component{row.id}"
            slug = _slugify(name)
            # Deduplicate slugs
            if slug in seen_slugs:
                slug = f"{slug}_{row.id}"
            seen_slugs.add(slug)
            components.append({"name": name, "slug": slug, "id": row.id})

        return components
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not load application components: %s", exc)
        return []


def _load_data_objects(solution_id: int) -> list:
    """Return a list of {name, slug, cls} dicts for data-layer elements."""
    try:
        from app.models.solution_archimate_element import SolutionArchiMateElement

        # DataObjects use layer_type "data" in the ArchiMate model
        rows = SolutionArchiMateElement.query.filter(
            SolutionArchiMateElement.solution_id == solution_id,
            SolutionArchiMateElement.layer_type.in_(["data", "data_object", "DataObject"]),
        ).all()

        seen_slugs: set = set()
        objects = []
        for row in rows:
            name = (row.element_name or "").strip() or f"DataObject{row.id}"
            slug = _slugify(name)
            if slug in seen_slugs:
                slug = f"{slug}_{row.id}"
            seen_slugs.add(slug)
            objects.append({"name": name, "slug": slug, "cls": _to_class_name(name)})

        return objects
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not load data objects: %s", exc)
        return []


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _render(solution_id: int, components: list, data_objects: list) -> dict:
    """Render all template files and return the {filename: content} dict."""
    files: dict = {}

    # ── Router files ──────────────────────────────────────────────────────
    for comp in components:
        slug = comp["slug"]
        name = comp["name"]
        content = _ROUTER_T.substitute(
            title=name,
            slug=slug,
            fn=slug,
        )
        files[f"routers/{slug}.py"] = content

    # ── Pydantic model files ───────────────────────────────────────────────
    for obj in data_objects:
        content = _MODEL_T.substitute(
            title=obj["name"],
            cls=obj["cls"],
        )
        files[f"models/{obj['slug']}.py"] = content

    # ── main.py ───────────────────────────────────────────────────────────
    import_lines = "\n".join(
        f"from routers.{c['slug']} import router as {c['slug']}_router"
        for c in components
    )
    include_lines = "\n".join(
        f"app.include_router({c['slug']}_router)"
        for c in components
    )
    component_list_str = ", ".join(c["name"] for c in components)
    files["main.py"] = _MAIN_T.substitute(
        solution_id=solution_id,
        component_list=component_list_str,
        imports=import_lines,
        includes=include_lines,
    )

    # ── docker-compose.yml ────────────────────────────────────────────────
    base_port = 8000
    service_blocks = []
    for i, comp in enumerate(components):
        service_blocks.append(
            _DOCKER_SERVICE_T.substitute(
                slug=comp["slug"],
                port=base_port + i,
            )
        )
    files["docker-compose.yml"] = _DOCKER_COMPOSE_T.substitute(
        services="\n".join(service_blocks),
    )

    # ── README.md ─────────────────────────────────────────────────────────
    from datetime import datetime, timezone

    comp_rows = "\n".join(
        f"| {c['name']} | `routers/{c['slug']}.py` | port {8000 + i} |"
        for i, c in enumerate(components)
    )
    components_table = (
        "| Component | Router file | Port |\n"
        "|-----------|-------------|------|\n"
        + comp_rows
    )
    router_tree = "\n".join(f"├── {c['slug']}.py" for c in components)
    model_tree = (
        "\n".join(f"├── {obj['slug']}.py" for obj in data_objects)
        if data_objects
        else "(none — add DataObject elements in the ArchiMate composer)"
    )

    files["README.md"] = _README_T.substitute(
        solution_id=solution_id,
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        components_table=components_table,
        router_tree=router_tree,
        model_tree=model_tree,
    )

    return files


def generate_zip(solution_id: int) -> bytes:
    """Generate the FastAPI scaffold and return it as an in-memory ZIP archive."""
    files = generate(solution_id)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for filename, content in files.items():
            zf.writestr(filename, content)
    return buf.getvalue()
