"""Deploy routes for the Code Workbench.

Covers:
- /codegen/deploy            (POST) — push generated code to GitHub via PR
- /codegen/download-iac      (GET)  — download Terraform IaC as ZIP
- /codegen/generate-iac      (POST) — generate Terraform IaC from ArchiMate elements
- /codegen/deploy-iac        (POST) — push IaC to GitHub via PR
- /codegen/deploy-cloud      (POST/GET/DELETE) — deploy to Coolify
- /codegen/recommend-language (GET)

Registered on ``codegen_bp`` (defined in codegen_routes.py).
Imported at the bottom of codegen_routes.py so routes attach automatically.
"""
import io
import logging
import re
import zipfile

from flask import jsonify, request, send_file
from flask_login import login_required

from app.extensions import db
from app.modules.codegen.models import CodegenGeneration
from app.models.solution_models import Solution
from app.utils.csrf_helper import require_csrf

from .codegen_routes import codegen_bp
from ._helpers import _check_access, _classify_tech_element, _build_terraform_files

logger = logging.getLogger(__name__)


# ── Deploy to GitHub (generated code) ────────────────────────────────────────

@codegen_bp.route("/solutions/<int:solution_id>/codegen/deploy", methods=["POST"])
@login_required
@require_csrf
def deploy_to_github(solution_id):
    """Push generated code to GitHub via pull request (GAP-05)."""
    solution = Solution.query.get_or_404(solution_id)
    if not _check_access(solution):
        return jsonify({"error": "Access denied"}), 403

    payload = request.get_json(silent=True) or {}
    gen = CodegenGeneration.query.filter_by(solution_id=solution_id).first()
    if not gen or not gen.generated_files:
        return jsonify({"error": "Generate code first (Phase 4)"}), 400

    if payload.get("version") and payload["version"] != gen.version:
        return jsonify({"error": "Version conflict. Refresh the page."}), 409

    config = gen.config or {}
    org = config.get("github_org", "")
    repo_name = config.get("repo_name", "")
    language = config.get("language", "python-fastapi")
    if not repo_name:
        return jsonify({"error": "Configure repository name first (Phase 3)"}), 400

    from app.models.models import APISettings
    gh_settings = APISettings.query.filter_by(provider="github").first()
    if not gh_settings or not gh_settings.api_key:
        return jsonify({"error": "No GitHub token configured. Go to Admin > API Settings."}), 400

    from app.modules.codegen.services.github_service import GitHubService
    gh = GitHubService(gh_settings.api_key)

    result = gh.create_repo(
        org=org, name=repo_name,
        private=config.get("visibility", "private") == "private",
        description=f"Generated from Entelim Architecture Journey — Solution #{solution_id}"
    )
    if not result["success"]:
        return jsonify(result), 400

    owner = result["full_name"].split("/")[0] if "/" in result.get("full_name", "") else (org or "user")
    default_branch = result.get("default_branch", "main")
    solution_slug = (solution.name or "").lower().replace(" ", "-")[:30] or f"solution-{solution_id}"

    commit_msg = (
        f"feat: scaffold from Architecture Journey — Solution #{solution_id}\n\n"
        f"Generated from ArchiMate 3.2 architecture by Entelim\n"
        f"{len(gen.generated_files)} source files\n\n"
        f"Traceability: see ARCHITECTURE.md"
    )
    pr_title = f"Generated: {solution.name or 'Solution'} ({language})"
    pr_body = (
        f"## Generated Code\n\n"
        f"- **Solution:** [{solution.name}](/solutions/{solution_id})\n"
        f"- **Language:** {language}\n"
        f"- **Files:** {len(gen.generated_files)}\n"
        f"- **Generated by:** Entelim Code Workbench\n\n"
        f"See `ARCHITECTURE.md` for ArchiMate traceability."
    )

    deploy_result = gh.deploy_via_pr(
        owner=owner, repo=repo_name, files=gen.generated_files,
        commit_message=commit_msg, pr_title=pr_title, pr_body=pr_body,
        default_branch=default_branch, branch_slug=f"codegen-{solution_slug}",
    )
    if not deploy_result["success"]:
        return jsonify(deploy_result), 400

    gen.github_url = result["url"]
    gen.github_pr_url = deploy_result.get("pr_url")
    gen.github_commit_sha = deploy_result["commit_sha"]
    gen.version += 1
    db.session.commit()

    response = {
        "success": True,
        "github_url": result["url"],
        "pr_url": deploy_result.get("pr_url"),
        "commit_sha": deploy_result["commit_sha"],
        "branch": deploy_result.get("branch"),
    }
    if deploy_result.get("warning"):
        response["warning"] = deploy_result["warning"]
    return jsonify(response)


# ── Download IaC ZIP ──────────────────────────────────────────────────────────

@codegen_bp.route("/solutions/<int:solution_id>/codegen/download-iac")
@login_required
def download_iac_zip(solution_id):
    """Download Terraform IaC for a solution as a standalone ZIP.

    Does NOT require a prior CodegenGeneration row — reads ArchiMate Technology
    layer elements directly and generates Terraform HCL on-the-fly.  Used by the
    journey wizard Step 7 "Get Infrastructure Code" button.
    """
    solution = Solution.query.get_or_404(solution_id)
    if not _check_access(solution):
        return jsonify({"error": "Access denied"}), 403

    region = request.args.get("region", "eu-west-1")
    environment = request.args.get("environment", "staging")

    from app.models.solution_archimate_element import SolutionArchiMateElement
    from app.models.archimate_core import ArchiMateElement as _AE

    tech_junctions = SolutionArchiMateElement.query.filter_by(
        solution_id=solution_id,
        layer_type="technology",
    ).all()

    classified = []
    for jxn in tech_junctions:
        elem_type = None
        try:
            ae = _AE.query.get(jxn.element_id)
            elem_type = ae.type if ae else None
        except Exception as exc:
            logger.debug("suppressed error in download_iac_zip (app/modules/codegen/routes/deploy_routes.py): %s", exc)
        classified.append({
            "name": jxn.element_name or "unknown",
            "type": elem_type or "unknown",
            "resource_type": _classify_tech_element(jxn.element_name, elem_type),
        })

    sol_slug = re.sub(r"[^a-z0-9]", "_", (solution.name or "solution").lower()).strip("_") or f"svc_{solution_id}"
    solutions_data = [{
        "id": solution_id,
        "name": solution.name or f"Solution {solution_id}",
        "slug": sol_slug,
        "port": 8000,
        "role": "primary",
    }]
    tf_files = _build_terraform_files(
        solution.name, solutions_data, {solution_id: classified}, region, environment
    )

    if not tf_files:
        return jsonify({"error": "No Technology layer elements linked. Add ArchiMate Node or SystemSoftware elements first."}), 400

    repo_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", (solution.name or f"solution-{solution_id}").strip())[:64] or f"solution-{solution_id}"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for filepath, content in tf_files.items():
            if ".." in filepath or filepath.startswith("/"):
                continue
            zf.writestr(f"{repo_name}-iac/{filepath}", content)
        # Add a minimal README with deploy instructions
        zf.writestr(
            f"{repo_name}-iac/DEPLOY.md",
            f"# Infrastructure — {solution.name or 'Solution'}\n\n"
            f"Generated by Entelim from ArchiMate Technology layer elements.\n\n"
            f"## Quick Start\n\n"
            f"```bash\ncd terraform/\nterraform init\nterraform plan -var=\"environment={environment}\" -var=\"region={region}\"\nterraform apply\n```\n\n"
            f"## Requirements\n\n- Terraform >= 1.5\n- AWS credentials configured (`aws configure` or environment variables)\n- Target environment: `{environment}` / Region: `{region}`\n\n"
            f"## Files\n\n"
            + "\n".join(f"- `{k}`" for k in sorted(tf_files.keys()))
            + "\n\n> For full workbench features (GitHub PR, SAP CAP, Azure Bicep), use the Advanced Workbench.\n"
        )

    buf.seek(0)
    return send_file(
        buf,
        mimetype="application/zip",
        as_attachment=True,
        download_name=f"{repo_name}-iac.zip",
    )


# ── Generate IaC (Terraform from ArchiMate) ───────────────────────────────────

@codegen_bp.route("/solutions/<int:solution_id>/codegen/generate-iac", methods=["POST"])
@login_required
@require_csrf
def generate_iac(solution_id):
    """Generate Terraform IaC files from this solution's Technology layer ArchiMate elements.

    Reads SolutionArchiMateElement rows with layer_type='technology', classifies each
    element to an AWS resource type, generates Terraform HCL, and merges the files into
    the solution's CodegenGeneration.generated_files JSON blob.
    """
    solution = Solution.query.get_or_404(solution_id)
    if not _check_access(solution):
        return jsonify({"error": "Access denied"}), 403

    payload = request.get_json(silent=True) or {}
    region = (payload.get("region") or "eu-west-1").strip()
    environment = (payload.get("environment") or "staging").strip()

    from app.models.solution_archimate_element import SolutionArchiMateElement
    from app.models.archimate_core import ArchiMateElement as _AE

    # Collect Technology layer elements linked to this solution
    tech_junctions = SolutionArchiMateElement.query.filter_by(
        solution_id=solution_id,
        layer_type="technology",
    ).all()

    classified = []
    for jxn in tech_junctions:
        elem_type = None
        try:
            ae = _AE.query.get(jxn.element_id)
            elem_type = ae.type if ae else None
        except Exception as _ae_exc:
            logger.debug("Could not load ArchiMate element type for %s: %s", jxn.element_id, _ae_exc)
        resource_type = _classify_tech_element(jxn.element_name, elem_type)
        classified.append({
            "name": jxn.element_name or "unknown",
            "type": elem_type or "unknown",
            "resource_type": resource_type,
        })

    sol_slug = re.sub(r"[^a-z0-9]", "_", (solution.name or "solution").lower()).strip("_") or "svc_{}".format(solution_id)
    solutions_data = [{
        "id": solution_id,
        "name": solution.name or "Solution {}".format(solution_id),
        "slug": sol_slug,
        "port": 8000,
        "role": "primary",
    }]
    tech_elements_by_solution = {solution_id: classified}

    tf_files = _build_terraform_files(solution.name, solutions_data, tech_elements_by_solution, region, environment)

    if not tf_files:
        return jsonify({"error": "No Terraform files generated — add Technology layer elements to this solution first."}), 400

    # Merge into generated_files
    gen = CodegenGeneration.query.filter_by(solution_id=solution_id).first()
    if not gen:
        return jsonify({"error": "Run Phase 1 (Generate Code) before generating IaC"}), 400

    existing = dict(gen.generated_files or {})
    existing.update(tf_files)
    gen.generated_files = existing
    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        logger.error("generate_iac DB commit failed for solution %s: %s", solution_id, e)
        return jsonify({"error": "Database error saving IaC files"}), 500

    all_elems = classified
    resource_summary = {
        "ecs_services": 1,
        "rds_instances": sum(1 for e in all_elems if e["resource_type"] == "aws_db_instance"),
        "elasticache_clusters": sum(1 for e in all_elems if e["resource_type"] == "aws_elasticache_cluster"),
        "albs": 1 if any(e["resource_type"] == "aws_lb" for e in all_elems) else 0,
        "s3_buckets": sum(1 for e in all_elems if e["resource_type"] == "aws_s3_bucket"),
        "vpc": 1,
    }

    return jsonify({
        "success": True,
        "file_count": len(tf_files),
        "files": list(tf_files.keys()),
        "resource_summary": resource_summary,
        "tech_element_count": len(classified),
        "region": region,
        "environment": environment,
    })


# ── Deploy IaC to GitHub ──────────────────────────────────────────────────────

@codegen_bp.route("/solutions/<int:solution_id>/codegen/deploy-iac", methods=["POST"])
@login_required
@require_csrf
def deploy_iac_to_github(solution_id):
    """Push IaC (Terraform) files to GitHub via pull request.

    Body: {"owner": "org-or-user", "repo": "repo-name", "base_branch": "main"} (all optional)
    Uses APISettings provider="github" for the PAT token.
    Uses the terraform/* subset of CodegenGeneration.generated_files.
    """
    solution = Solution.query.get_or_404(solution_id)
    if not _check_access(solution):
        return jsonify({"error": "Access denied"}), 403

    gen = CodegenGeneration.query.filter_by(solution_id=solution_id).first()
    if not gen or not gen.generated_files:
        return jsonify({"error": "Generate IaC first (click 'Generate Terraform IaC')"}), 400

    tf_files = {k: v for k, v in gen.generated_files.items() if k.startswith("terraform/")}
    if not tf_files:
        return jsonify({"error": "No Terraform files found. Generate IaC first."}), 400

    from app.models.models import APISettings
    gh_settings = APISettings.query.filter_by(provider="github").first()
    if not gh_settings or not gh_settings.api_key:
        return jsonify({"error": "No GitHub token configured. Go to Admin > API Settings and add provider='github'."}), 400

    payload = request.get_json(silent=True) or {}
    config = gen.config or {}
    owner = (payload.get("owner") or config.get("github_org") or "").strip()
    repo = (payload.get("repo") or config.get("repo_name") or "").strip()
    base_branch = (payload.get("base_branch") or "main").strip()

    if not owner or not repo:
        return jsonify({"error": "Provide 'owner' and 'repo' in the request body."}), 400

    from app.modules.codegen.services.github_service import GitHubService
    gh = GitHubService(gh_settings.api_key)

    solution_slug = re.sub(r"[^a-z0-9]", "-", (solution.name or "solution").lower()).strip("-")[:30] or f"solution-{solution_id}"
    commit_msg = (
        f"feat(iac): Terraform infrastructure for {solution.name or 'Solution'} #{solution_id}\n\n"
        f"Generated from Technology layer ArchiMate elements by Entelim\n"
        f"{len(tf_files)} Terraform files"
    )
    pr_title = f"IaC: {solution.name or 'Solution'} Terraform infrastructure"
    pr_body = (
        f"## Infrastructure as Code\n\n"
        f"Generated Terraform from the Technology layer of [{solution.name}](/solutions/{solution_id}).\n\n"
        f"**Files ({len(tf_files)}):**\n"
        + "\n".join(f"- `{k}`" for k in sorted(tf_files.keys()))
        + "\n\n> Generated by Entelim Code Workbench"
    )

    result = gh.deploy_via_pr(
        owner=owner, repo=repo, files=tf_files,
        commit_message=commit_msg, pr_title=pr_title, pr_body=pr_body,
        default_branch=base_branch, branch_slug=f"iac-{solution_slug}",
    )

    if result.get("success"):
        gen.github_pr_url = result.get("pr_url") or gen.github_pr_url
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()

    return jsonify(result), 200 if result.get("success") else 400


# ─── Entelim Deploy: Coolify deployment routes ─────────────────────────────────
# Design spec: docs/2026-03-30-archie-deploy-zero-dev-design.md §1


@codegen_bp.route(
    "/solutions/<int:solution_id>/codegen/deploy-cloud", methods=["POST"]
)
@login_required
def deploy_to_coolify(solution_id):
    """Deploy generated code to Coolify-managed infrastructure."""
    solution = Solution.query.get_or_404(solution_id)
    _check_access(solution)

    gen = CodegenGeneration.query.filter_by(solution_id=solution_id).first()
    if not gen or not gen.generated_files:
        return jsonify({"error": "No generated code found. Run code generation first."}), 400

    language = gen.config.get("language", "python-fastapi") if gen.config else "python-fastapi"
    code_files = gen.generated_files
    if not isinstance(code_files, dict):
        return jsonify({"error": "Generated files format invalid."}), 400

    try:
        from app.modules.codegen.services.instance_tracker import InstanceTracker
        from app.modules.codegen.services.deployment_orchestrator import DeploymentOrchestrator

        tracker = InstanceTracker()
        tracker.check_quota()

        orch = DeploymentOrchestrator()
        instance = orch.deploy(
            solution_id=solution_id,
            language=language,
            code_files=code_files,
        )
        return jsonify({
            "status": "deploying",
            "deployment_url": instance.deployment_url,
            "version": instance.version,
            "instance_id": instance.id,
            "message": "Your solution is being deployed. Check status for updates.",
        }), 202

    except RuntimeError as e:
        return jsonify({"error": str(e)}), 503


@codegen_bp.route(
    "/solutions/<int:solution_id>/codegen/deploy-cloud/status", methods=["GET"]
)
@login_required
def deploy_status(solution_id):
    """Check deployment status for a solution."""
    solution = Solution.query.get_or_404(solution_id)
    _check_access(solution)

    from app.modules.codegen.services.instance_tracker import InstanceTracker

    tracker = InstanceTracker()
    instance = tracker.get_instance(solution_id=solution_id)
    if not instance:
        return jsonify({"status": "not_deployed", "message": "No deployment found for this solution."}), 404

    if instance.health_status == "deploying":
        try:
            from app.modules.codegen.services.deployment_orchestrator import DeploymentOrchestrator
            orch = DeploymentOrchestrator()
            orch.health_check(instance.id)
        except Exception as exc:
            logger.debug("suppressed error in deploy_status (app/modules/codegen/routes/deploy_routes.py): %s", exc)

    return jsonify({
        "status": instance.health_status,
        "deployment_url": instance.deployment_url,
        "version": instance.version,
        "deployed_at": instance.deployed_at.isoformat() if instance.deployed_at else None,
        "last_health_check": instance.last_health_check.isoformat() if instance.last_health_check else None,
        "instance_id": instance.id,
    })


@codegen_bp.route(
    "/solutions/<int:solution_id>/codegen/deploy-cloud", methods=["DELETE"]
)
@login_required
def deploy_destroy(solution_id):
    """Stop and remove a deployed solution."""
    solution = Solution.query.get_or_404(solution_id)
    _check_access(solution)

    from app.modules.codegen.services.instance_tracker import InstanceTracker
    from app.modules.codegen.services.deployment_orchestrator import DeploymentOrchestrator

    tracker = InstanceTracker()
    instance = tracker.get_instance(solution_id=solution_id)
    if not instance:
        return jsonify({"error": "No deployment found."}), 404

    try:
        orch = DeploymentOrchestrator()
        orch.destroy(instance.id)
        return jsonify({"status": "stopped", "message": "Deployment destroyed."})
    except Exception as e:
        logger.exception("Failed to destroy deployment for solution %s", solution_id)
        return jsonify({"error": f"Destroy failed: {e}"}), 500


@codegen_bp.route(
    "/solutions/<int:solution_id>/codegen/recommend-language", methods=["GET"]
)
@login_required
def recommend_language_route(solution_id):
    """Recommend the best programming language for this solution."""
    solution = Solution.query.get_or_404(solution_id)
    _check_access(solution)

    from app.modules.codegen.services.deployment_orchestrator import recommend_language

    elements = []
    if hasattr(solution, "archimate_elements"):
        for junction in solution.archimate_elements:
            el = junction.archimate_element if hasattr(junction, "archimate_element") else None
            if el:
                props = {}
                if hasattr(junction, "spec_data") and isinstance(junction.spec_data, dict):
                    props = junction.spec_data
                elements.append({
                    "type": el.element_type if hasattr(el, "element_type") else "",
                    "properties": props,
                })

    recommendation = recommend_language(elements)
    return jsonify(recommendation)
