"""add_usage_analytics_table

Revision ID: 20260203_add_usage_analytics_table
Revises: 20260203_add_strategic_recommendations
Create Date: 2026-02-03 22:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260203_add_usage_analytics_table'
down_revision = '20260203_add_strategic_recommendations'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_analytics_event_type'), 'usage_analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_analytics_feature_name'), 'usage_analytics', ['feature_name'], unique=False)
    op.create_index(op.f('ix_usage_analytics_session_id'), 'usage_analytics', ['session_id'], unique=False)
    op.create_index(op.f('ix_usage_analytics_timestamp'), 'usage_analytics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_analytics_timestamp'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_session_id'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_feature_name'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_event_type'), table_name='usage_analytics')
    op.drop_table('usage_analytics')
    # ### end Alembic commands ###