"""Add missing code column to business_capability table

Revision ID: add_capability_code_column
Revises: fix_phase4_relationships
Create Date: 2026-01-09 02:10:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_capability_code_column"
down_revision = "add_huggingface_fields"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("business_capability", sa.Column("code", sa.String(length=50), nullable=True))
    op.create_index(
        op.f("ix_business_capability_code"), "business_capability", ["code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_business_capability_code"), table_name="business_capability")
    op.drop_column("business_capability", "code")
    # ### end Alembic commands ###
