"""Add HuggingFace fields to models

Revision ID: add_huggingface_fields
Revises: fix_phase4_relationships
Create Date: 2026-01-09 02:10:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_huggingface_fields"
down_revision = "fix_phase4_relationships"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
