# mass-deletion-ok
"""
GitIntegrationService — Push generated code to GitHub repos.

Uses subprocess with git/curl commands. No PyGithub dependency.
GitHub PAT stored in APISettings table (same pattern as LLM keys).
"""
import json
import logging
import os
import re
import shutil
import subprocess
import tempfile

logger = logging.getLogger(__name__)


class GitIntegrationService:
    """Push generated code to GitHub repos instead of ZIP downloads."""

    def __init__(self):
        self.github_token = self._get_github_token()
        self.org = self._get_org_name()

    def _get_github_token(self):
        """Get GitHub PAT from APISettings table (same pattern as LLM keys)."""
        try:
            from app.models.models import APISettings
            setting = APISettings.query.filter_by(provider="github").first()
            if setting and setting.api_key:
                return setting.api_key
        except Exception as e:
            logger.debug("Could not load GitHub token from DB: %s", e)
        return os.environ.get("GITHUB_TOKEN")

    def _get_org_name(self):
        """Get GitHub org/user from env. Defaults to 'archie-generated'."""
        return os.environ.get("GITHUB_ORG", "archie-generated")

    @staticmethod
    def _sanitize_repo_name(name):
        """Convert a solution name to a valid GitHub repo name."""
        name = name.lower().strip()
        name = re.sub(r"[^a-z0-9\-]", "-", name)
        name = re.sub(r"-+", "-", name).strip("-")
        return name[:100] if name else "unnamed"

    def create_repo_and_push(self, solution_id, bundle, repo_name=None):
        """Create GitHub repo and push generated code.

        Args:
            solution_id: int
            bundle: GeneratedCodeBundle (from DeterministicCodeGenerator)
            repo_name: optional custom name (default: solution-{id}-{sanitized_name})

        Returns:
            dict with keys: success, repo_url, error
        """
        if not self.github_token:
            return {
                "success": False,
                "error": (
                    "GitHub token not configured. "
                    "Add it at /admin/api-settings with provider='github'."
                ),
            }

        # Determine repo name
        if not repo_name:
            try:
                from app.models.solution_models import Solution
                sol = Solution.query.get(solution_id)
                sol_name = self._sanitize_repo_name(sol.name) if sol else str(solution_id)
            except Exception:
                sol_name = str(solution_id)
            repo_name = f"solution-{solution_id}-{sol_name}"

        tmp_dir = None
        try:
            # 1. Write files to temp directory
            tmp_dir = tempfile.mkdtemp(prefix="archie-git-")
            project_dir = os.path.join(tmp_dir, repo_name)
            os.makedirs(project_dir, exist_ok=True)

            for f in bundle.files:
                file_path = os.path.join(project_dir, f.path)
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                with open(file_path, "w", encoding="utf-8") as fh:
                    fh.write(f.content)

            # Write GENERATED.md with spec hash for drift detection
            generated_md = (
                f"# Generated by Entelim\n\n"
                f"**Solution ID:** {solution_id}\n"
                f"**Bundle ID:** {bundle.bundle_id}\n"
                f"**Language:** {bundle.language}\n"
                f"**Spec Hash:** {bundle.spec_hash}\n"
                f"**File Count:** {len(bundle.files)}\n\n"
                f"Do not edit generated files directly. "
                f"Changes will be overwritten on next generation.\n"
            )
            with open(os.path.join(project_dir, "GENERATED.md"), "w", encoding="utf-8") as fh:
                fh.write(generated_md)

            # Write .gitignore
            gitignore = (
                "__pycache__/\n*.pyc\n.env\n.venv/\nvenv/\n"
                "*.egg-info/\ndist/\nbuild/\n.pytest_cache/\n"
                "node_modules/\n.DS_Store\n"
            )
            with open(os.path.join(project_dir, ".gitignore"), "w", encoding="utf-8") as fh:
                fh.write(gitignore)

            # 2. Create GitHub repo via API
            create_result = self._create_github_repo(repo_name)
            if not create_result["success"]:
                return create_result

            repo_url = create_result["repo_url"]
            clone_url = create_result["clone_url"]

            # 3. Git init, add, commit, push
            env = os.environ.copy()
            env["GIT_TERMINAL_PROMPT"] = "0"

            cmds = [
                ["git", "init"],
                ["git", "config", "user.email", "archie@generated.local"],
                ["git", "config", "user.name", "Entelim Code Generator"],
                ["git", "add", "."],
                ["git", "commit", "-m",
                 f"feat: initial generation from solution {solution_id}\n\n"
                 f"spec_hash: {bundle.spec_hash}\n"
                 f"bundle_id: {bundle.bundle_id}\n"
                 f"language: {bundle.language}\n"
                 f"file_count: {len(bundle.files)}"],
                ["git", "branch", "-M", "main"],
                ["git", "remote", "add", "origin", clone_url],
                ["git", "push", "-u", "origin", "main"],
            ]

            for cmd in cmds:
                result = subprocess.run(
                    cmd,
                    cwd=project_dir,
                    capture_output=True,
                    text=True,
                    env=env,
                    timeout=60,
                )
                if result.returncode != 0:
                    logger.error(
                        "Git command failed: %s — stderr: %s",
                        " ".join(cmd[:3]),
                        result.stderr[:500],
                    )
                    return {
                        "success": False,
                        "error": f"Git command failed: {' '.join(cmd[:3])}",
                        "detail": result.stderr[:500],
                    }

            logger.info(
                "Pushed solution %s to %s (%d files)",
                solution_id, repo_url, len(bundle.files),
            )

            return {
                "success": True,
                "repo_url": repo_url,
                "branch": "main",
                "file_count": len(bundle.files),
                "spec_hash": bundle.spec_hash,
            }

        except subprocess.TimeoutExpired:
            return {"success": False, "error": "Git operation timed out (60s limit)."}
        except Exception as e:
            logger.exception("Git integration failed for solution %s", solution_id)
            return {"success": False, "error": str(e)}
        finally:
            if tmp_dir and os.path.exists(tmp_dir):
                shutil.rmtree(tmp_dir, ignore_errors=True)

    def _create_github_repo(self, repo_name):
        """Create a GitHub repo via the REST API using curl.

        Returns: {"success": bool, "repo_url": str, "clone_url": str, "error": str}
        """
        # Check if repo already exists under org
        check_url = f"https://api.github.com/repos/{self.org}/{repo_name}"
        check = subprocess.run(
            [
                "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
                "-H", f"Authorization: token {self.github_token}",
                "-H", "Accept: application/vnd.github+json",
                check_url,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )

        if check.stdout.strip() == "200":
            # Repo already exists — reuse it
            return {
                "success": True,
                "repo_url": f"https://github.com/{self.org}/{repo_name}",
                "clone_url": f"https://{self.github_token}@github.com/{self.org}/{repo_name}.git",
            }

        # Try creating under org first, fall back to user
        payload = json.dumps({
            "name": repo_name,
            "description": "Generated by Entelim — Solution Architecture Blueprint",
            "private": True,
            "auto_init": False,
        })

        # Try org endpoint
        create_url = f"https://api.github.com/orgs/{self.org}/repos"
        result = subprocess.run(
            [
                "curl", "-s",
                "-H", f"Authorization: token {self.github_token}",
                "-H", "Accept: application/vnd.github+json",
                "-H", "Content-Type: application/json",
                "-d", payload,
                create_url,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )

        try:
            data = json.loads(result.stdout)
        except (json.JSONDecodeError, ValueError):
            return {"success": False, "error": f"GitHub API returned invalid JSON: {result.stdout[:200]}"}

        if "html_url" in data:
            return {
                "success": True,
                "repo_url": data["html_url"],
                "clone_url": f"https://{self.github_token}@github.com/{self.org}/{repo_name}.git",
            }

        # Fall back to user repos (if org doesn't exist or no permission)
        if data.get("message", "").startswith("Not Found") or "organization" in data.get("message", "").lower():
            user_url = "https://api.github.com/user/repos"
            result = subprocess.run(
                [
                    "curl", "-s",
                    "-H", f"Authorization: token {self.github_token}",
                    "-H", "Accept: application/vnd.github+json",
                    "-H", "Content-Type: application/json",
                    "-d", payload,
                    user_url,
                ],
                capture_output=True,
                text=True,
                timeout=30,
            )

            try:
                data = json.loads(result.stdout)
            except (json.JSONDecodeError, ValueError):
                return {"success": False, "error": f"GitHub API returned invalid JSON: {result.stdout[:200]}"}

            if "html_url" in data:
                owner = data.get("owner", {}).get("login", self.org)
                return {
                    "success": True,
                    "repo_url": data["html_url"],
                    "clone_url": f"https://{self.github_token}@github.com/{owner}/{repo_name}.git",
                }

        error_msg = data.get("message", "Unknown GitHub API error")
        errors = data.get("errors", [])
        if errors:
            error_msg += f" — {errors[0].get('message', '')}"

        return {"success": False, "error": f"GitHub repo creation failed: {error_msg}"}
