"""
SeedDataGenerator — Generate realistic seed data from confirmed field definitions.

Produces SQL INSERT statements with heuristic data based on field names and types.
No LLM. No network. Deterministic output for the same input (uses sequential IDs
and predictable patterns rather than random values).
"""
import re
import uuid as _uuid_mod
from datetime import datetime, timedelta, timezone


# Number of seed rows generated per entity
DEFAULT_ROW_COUNT = 10

# ── Field name heuristics ───────────────────────────────────────────────────
# Maps field name patterns to data generator functions.
# Each generator receives (field_def, row_index) and returns a SQL-safe string.


def _sql_str(val):
    """Escape a string value for SQL."""
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def _sql_null():
    return "NULL"


def _gen_uuid(field_def, idx):
    """Generate a deterministic UUID based on index."""
    ns = _uuid_mod.NAMESPACE_DNS
    name = f"seed-{field_def.get('name', 'id')}-{idx}"
    return _sql_str(str(_uuid_mod.uuid5(ns, name)))


def _gen_name(field_def, idx):
    """Generate a descriptive name string."""
    base = field_def.get("name", "item").replace("_name", "").replace("name", "item")
    base = base.replace("_", " ").strip() or "item"
    return _sql_str(f"Sample {base.title()} {idx + 1}")


def _gen_email(field_def, idx):
    return _sql_str(f"user{idx + 1}@example.com")


def _gen_url(field_def, idx):
    entity = field_def.get("_entity_name", "resource")
    return _sql_str(f"https://example.com/{entity}/{idx + 1}")


def _gen_description(field_def, idx):
    entity = field_def.get("_entity_name", "entity")
    return _sql_str(
        f"Description for {entity} record {idx + 1}. "
        f"This is sample seed data generated by Entelim."
    )


def _gen_amount(field_def, idx):
    """Generate a decimal amount in a reasonable range."""
    base = 10.0 + (idx * 7.5)
    return f"{base:.2f}"


def _gen_count(field_def, idx):
    return str(1 + (idx * 3) % 100)


def _gen_boolean(field_def, idx):
    return "true" if idx % 2 == 0 else "false"


def _gen_timestamp(field_def, idx):
    """Generate a relative timestamp (today - N days)."""
    base = datetime(2026, 1, 15, 10, 0, 0, tzinfo=timezone.utc)
    dt = base - timedelta(days=idx)
    return _sql_str(dt.strftime("%Y-%m-%d %H:%M:%S+00"))


def _gen_date(field_def, idx):
    base = datetime(2026, 1, 15, tzinfo=timezone.utc)
    dt = base - timedelta(days=idx)
    return _sql_str(dt.strftime("%Y-%m-%d"))


def _gen_integer(field_def, idx):
    name = field_def.get("name", "")
    if "year" in name.lower():
        return str(2020 + (idx % 7))
    if "age" in name.lower():
        return str(25 + idx)
    if "port" in name.lower():
        return str(8000 + idx)
    return str(idx + 1)


def _gen_float(field_def, idx):
    return f"{(idx + 1) * 1.5:.2f}"


def _gen_enum(field_def, idx):
    """Cycle through enum values."""
    values = field_def.get("enum", [])
    if not values:
        return _sql_str("unknown")
    return _sql_str(values[idx % len(values)])


def _gen_string(field_def, idx):
    """Fallback string generator."""
    name = field_def.get("name", "field")
    return _sql_str(f"{name}_{idx + 1}")


def _gen_json(field_def, idx):
    return _sql_str("{}")


# ── Pattern matching ────────────────────────────────────────────────────────

_NAME_PATTERNS = [
    (re.compile(r"(^id$|_id$)"), None),  # handled separately (FK or PK)
    (re.compile(r"uuid", re.I), _gen_uuid),
    (re.compile(r"e?mail", re.I), _gen_email),
    (re.compile(r"(^url$|_url$|website|homepage)", re.I), _gen_url),
    (re.compile(r"(description|summary|notes|comment|bio)", re.I), _gen_description),
    (re.compile(r"(^name$|_name$|title|label)", re.I), _gen_name),
    (re.compile(r"(amount|price|cost|fee|salary|budget|revenue)", re.I), _gen_amount),
    (re.compile(r"(count|quantity|total|num_|number_of)", re.I), _gen_count),
    (re.compile(r"(^is_|^has_|^can_|^should_|enabled|active|visible)", re.I), _gen_boolean),
    (re.compile(r"(_at$|_time$|timestamp|created|updated|deleted|modified)", re.I), _gen_timestamp),
    (re.compile(r"(_date$|^date$|birth|expir)", re.I), _gen_date),
]


def _get_generator(field_def):
    """Select a data generator based on field name, type, and format."""
    name = field_def.get("name", "")
    ftype = field_def.get("type", "string")
    fmt = field_def.get("format", "")

    # Enum fields always cycle through values
    if ftype == "enum" or field_def.get("enum"):
        return _gen_enum

    # Format-based
    if fmt == "uuid":
        return _gen_uuid
    if fmt == "email":
        return _gen_email
    if fmt == "uri" or fmt == "url":
        return _gen_url
    if fmt == "date-time":
        return _gen_timestamp
    if fmt == "date":
        return _gen_date

    # Name-pattern matching
    for pattern, gen in _NAME_PATTERNS:
        if pattern.search(name):
            if gen is not None:
                return gen
            # _id pattern: skip (handled as FK/PK)
            return None

    # Type-based fallback
    if ftype in ("integer", "int", "int64"):
        return _gen_integer
    if ftype in ("number", "float", "float64", "decimal"):
        return _gen_float
    if ftype in ("boolean", "bool"):
        return _gen_boolean
    if ftype in ("object", "dict", "json", "jsonb"):
        return _gen_json
    if ftype in ("array", "list"):
        return _gen_json

    return _gen_string


def _snake(name):
    """Convert to snake_case."""
    s = re.sub(r"[^a-zA-Z0-9]", "_", (name or "unknown").strip())
    return re.sub(r"_+", "_", s).strip("_").lower()


class SeedDataGenerator:
    """Generate realistic seed data from confirmed field definitions.

    For each entity in the spec:
    - Generates N rows (default 10) of realistic sample data
    - String fields: meaningful placeholder based on field name
    - Integer fields: reasonable range based on context
    - Date fields: relative dates
    - Boolean fields: alternating true/false
    - Enum/status fields: cycle through allowed values
    - UUID fields: deterministic UUIDs
    - Email fields: user{n}@example.com pattern
    - Foreign keys: reference IDs from other seeded tables
    """

    def __init__(self, row_count=DEFAULT_ROW_COUNT):
        self.row_count = row_count

    def generate(self, confirmed_fields, solution_name="app"):
        """Generate seed data context for template rendering.

        Args:
            confirmed_fields: dict of entity_name -> list of field defs
            solution_name: used for URL generation

        Returns:
            List of entity dicts, each with:
            - name: entity display name
            - table_name: snake_case table name
            - columns: list of column names
            - rows: list of value tuples (SQL-formatted strings)
        """
        if not confirmed_fields:
            return []

        # First pass: determine entity order (entities without FKs first)
        entity_order = self._topological_sort(confirmed_fields)

        # Track generated PKs for FK references
        pk_map = {}  # table_name -> list of PK values

        entities = []
        for entity_name in entity_order:
            field_defs = confirmed_fields[entity_name]
            table_name = _snake(entity_name)

            # Separate PK, FK, and regular fields
            columns = []
            generators = []

            for fdef in field_defs:
                fname = fdef.get("name", "")
                if not fname:
                    continue

                # Annotate with entity name for context-aware generators
                fdef_copy = dict(fdef)
                fdef_copy["_entity_name"] = table_name

                # Skip auto-increment PKs (id field)
                if fname == "id" and not self._is_foreign_key(fname, fdef):
                    columns.append(fname)
                    generators.append(("pk", fdef_copy))
                    continue

                # Foreign key references
                if self._is_foreign_key(fname, fdef):
                    ref_table = self._resolve_fk_table(fname, fdef)
                    columns.append(fname)
                    generators.append(("fk", fdef_copy, ref_table))
                    continue

                gen = _get_generator(fdef_copy)
                if gen is None:
                    continue
                columns.append(fname)
                generators.append(("gen", fdef_copy, gen))

            # Skip entities with no usable columns
            if not columns:
                entities.append({
                    "name": entity_name,
                    "table_name": table_name,
                    "columns": [],
                    "rows": [],
                })
                continue

            # Generate rows
            rows = []
            pk_values = []
            for idx in range(self.row_count):
                row = []
                for entry in generators:
                    if entry[0] == "pk":
                        val = str(idx + 1)
                        pk_values.append(val)
                        row.append(val)
                    elif entry[0] == "fk":
                        ref_table = entry[2]
                        ref_pks = pk_map.get(ref_table, [])
                        if ref_pks:
                            row.append(ref_pks[idx % len(ref_pks)])
                        else:
                            row.append(str(idx + 1))
                    else:
                        gen_func = entry[2]
                        row.append(gen_func(entry[1], idx))
                rows.append(row)

            pk_map[table_name] = pk_values or [str(i + 1) for i in range(self.row_count)]

            entities.append({
                "name": entity_name,
                "table_name": table_name,
                "columns": columns,
                "rows": rows,
            })

        return entities

    @staticmethod
    def _is_foreign_key(fname, fdef):
        """Check if a field is a foreign key."""
        if fname == "id":
            return False
        if fname.endswith("_id"):
            return True
        if fdef.get("constraints", {}).get("foreign_key"):
            return True
        return False

    @staticmethod
    def _resolve_fk_table(fname, fdef):
        """Resolve the referenced table name from a FK field."""
        # Check explicit constraint
        fk = (fdef.get("constraints") or {}).get("foreign_key", "")
        if fk and "." in fk:
            return fk.split(".")[0]

        # Infer from field name: user_id -> user, order_item_id -> order_item
        if fname.endswith("_id"):
            return fname[:-3]
        return "unknown"

    def _topological_sort(self, confirmed_fields):
        """Sort entities so that referenced tables come before referencing ones."""
        entities = list(confirmed_fields.keys())
        table_names = {_snake(e) for e in entities}

        # Build dependency graph
        deps = {}
        for entity_name in entities:
            entity_deps = set()
            for fdef in confirmed_fields[entity_name]:
                fname = fdef.get("name", "")
                if self._is_foreign_key(fname, fdef):
                    ref = self._resolve_fk_table(fname, fdef)
                    if ref in table_names and ref != _snake(entity_name):
                        entity_deps.add(ref)
            deps[entity_name] = entity_deps

        # Simple topological sort (Kahn's algorithm)
        sorted_list = []
        remaining = set(entities)
        while remaining:
            # Find entities with no unsatisfied dependencies
            ready = []
            for e in remaining:
                unsatisfied = deps[e] - {_snake(s) for s in sorted_list}
                if not unsatisfied:
                    ready.append(e)

            if not ready:
                # Circular dependency — just add remaining in original order
                sorted_list.extend(sorted(remaining))
                break

            # Stable sort: pick alphabetically first
            ready.sort()
            sorted_list.append(ready[0])
            remaining.remove(ready[0])

        return sorted_list
