"""
Workflow Pipeline Models for LangGraph-based execution.

This is a separate system from GenerationPipeline to allow:
- User-customizable workflows with visual builder
- Conditional routing and branching logic
- Real-time cost controls and budget enforcement
- Template library for best practices
- Zero disruption to existing pipelines
"""
import logging
from datetime import datetime

from sqlalchemy import event
from sqlalchemy.orm import attributes

from app import db

_state_logger = logging.getLogger(__name__ + ".state_machine")

# Valid status transitions for EAWorkflowInstance
_WORKFLOW_TRANSITIONS = {
    "pending": {"running", "cancelled"},
    "running": {"waiting_approval", "completed", "failed", "cancelled"},
    "waiting_approval": {"running", "completed", "cancelled"},
    "completed": set(),  # terminal
    "failed": {"pending"},  # can retry
    "cancelled": set(),  # terminal
}


class WorkflowPipeline(db.Model):
    """
    Next-generation workflow-based pipeline with LangGraph.
    Completely separate from GenerationPipeline for zero risk.
    """

    __tablename__ = "workflow_pipelines"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)

    # Workflow definition (user-customizable graph)
    workflow_graph = db.Column(db.JSON, nullable=False)  # LangGraph JSON definition
    workflow_version = db.Column(db.Integer, default=1)

    # Template tracking
    template_id = db.Column(db.Integer, db.ForeignKey("workflow_templates.id"))
    is_template_instance = db.Column(db.Boolean, default=False)

    # Execution state
    status = db.Column(
        db.String(20), default="draft"
    )  # draft, pending, running, paused, completed, failed, cancelled
    current_node_id = db.Column(db.String(50))  # Currently executing node
    workflow_state = db.Column(db.JSON)  # Full LangGraph state for resume capability

    # Input configuration (similar to GenerationPipeline for compatibility)
    capability_ids = db.Column(db.Text)  # Comma-separated BusinessCapability IDs
    jira_project_id = db.Column(db.Integer, db.ForeignKey("jira_projects.id"))
    selected_issue_keys = db.Column(db.Text)  # Comma-separated JIRA keys
    platform_type_id = db.Column(db.Integer, db.ForeignKey("platform_types.id"))
    platform_config_id = db.Column(db.Integer, db.ForeignKey("platform_configurations.id"))
    technology_stack_id = db.Column(db.Integer, db.ForeignKey("technology_stacks.id"))

    # Cost tracking and budget enforcement
    budget_limit = db.Column(db.Float)  # Max $ to spend on LLM calls
    cost_accumulated = db.Column(db.Float, default=0.0)
    cost_alert_threshold = db.Column(db.Float)  # Alert when cost reaches this amount
    stop_on_budget_exceeded = db.Column(db.Boolean, default=True)

    # Quality gates
    require_human_approval = db.Column(db.Boolean, default=False)
    approval_stage_node_id = db.Column(db.String(50))  # Node where approval is required
    approved_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    approved_at = db.Column(db.DateTime)

    # Execution metadata
    execution_mode = db.Column(
        db.String(20), default="sequential"
    )  # sequential, parallel, adaptive
    max_retry_attempts = db.Column(db.Integer, default=3)
    timeout_minutes = db.Column(db.Integer, default=60)

    # Output artifacts (generated by workflow)
    architecture_id = db.Column(db.Integer, db.ForeignKey("architecture_models.id"))
    output_artifacts = db.Column(db.JSON)  # Links to generated code, requirements, etc.

    # Background job tracking
    job_id = db.Column(db.String(50))  # Flask-RQ2 job ID for async execution

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    started_at = db.Column(db.DateTime)
    completed_at = db.Column(db.DateTime)
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)

    # Relationships
    nodes = db.relationship(
        "WorkflowNode", backref="pipeline", cascade="all, delete-orphan", lazy="dynamic"
    )
    edges = db.relationship(
        "WorkflowEdge", backref="pipeline", cascade="all, delete-orphan", lazy="dynamic"
    )
    executions = db.relationship(
        "WorkflowExecution", backref="pipeline", cascade="all, delete-orphan", lazy="dynamic"
    )

    # Foreign key relationships
    platform_type = db.relationship("PlatformType")
    platform_config = db.relationship("PlatformConfiguration")
    technology_stack = db.relationship("TechnologyStack")
    template = db.relationship(
        "WorkflowTemplate", foreign_keys=[template_id], overlaps="source_template,instances"
    )
    created_by = db.relationship("User", foreign_keys=[created_by_id])
    approved_by = db.relationship("User", foreign_keys=[approved_by_id])
    architecture = db.relationship("ArchitectureModel")

    @property
    def duration_seconds(self):
        """Calculate duration if pipeline has started and completed."""
        if self.started_at and self.completed_at:
            return int((self.completed_at - self.started_at).total_seconds())
        return None

    @property
    def budget_remaining(self):
        """Calculate remaining budget."""
        if self.budget_limit:
            return self.budget_limit - self.cost_accumulated
        return None

    @property
    def is_over_budget(self):
        """Check if pipeline has exceeded budget."""
        if self.budget_limit:
            return self.cost_accumulated >= self.budget_limit
        return False

    def __repr__(self):
        return f"<WorkflowPipeline {self.id}: {self.name}>"


class WorkflowNode(db.Model):
    """
    Individual nodes in the workflow graph.
    Each node represents an operation (LLM call, validation, code gen, etc.)
    """

    __tablename__ = "workflow_nodes"

    id = db.Column(db.Integer, primary_key=True)
    pipeline_id = db.Column(db.Integer, db.ForeignKey("workflow_pipelines.id"), nullable=False)

    # Node identification
    node_id = db.Column(
        db.String(50), nullable=False
    )  # e.g., "capability_sync_1", "llm_architect_2"
    node_type = db.Column(db.String(50), nullable=False)  # From NodeRegistry
    label = db.Column(db.String(100))
    description = db.Column(db.Text)

    # Visual builder position
    position_x = db.Column(db.Integer, default=0)
    position_y = db.Column(db.Integer, default=0)

    # Node configuration (type-specific settings)
    config = db.Column(db.JSON)  # JSON config for this node type

    # Execution state
    status = db.Column(
        db.String(20), default="pending"
    )  # pending, running, completed, failed, skipped
    output_data = db.Column(db.JSON)  # Output from this node
    error_message = db.Column(db.Text)
    retry_count = db.Column(db.Integer, default=0)

    # Execution metrics
    started_at = db.Column(db.DateTime)
    completed_at = db.Column(db.DateTime)
    duration_seconds = db.Column(db.Integer)

    # Cost tracking (for LLM nodes)
    cost = db.Column(db.Float, default=0.0)
    llm_provider = db.Column(db.String(20))  # 'openai', 'anthropic', 'azure'
    llm_model = db.Column(db.String(50))
    tokens_input = db.Column(db.Integer)
    tokens_output = db.Column(db.Integer)

    # Validation (for validator nodes)
    validation_rules = db.Column(db.JSON)
    validation_passed = db.Column(db.Boolean)

    # Human approval (for approval nodes)
    requires_approval = db.Column(db.Boolean, default=False)
    approved_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    approved_at = db.Column(db.DateTime)
    approval_comment = db.Column(db.Text)

    # Relationships
    approved_by = db.relationship("User")

    def __repr__(self):
        return f"<WorkflowNode {self.node_id}: {self.node_type}>"


class WorkflowCleanupNode(db.Model):
    """
    Specialized node for cleaning up temporary files and artifacts.
    Automatically removes files based on patterns and retention policies.
    """

    __tablename__ = "workflow_cleanup_nodes"

    id = db.Column(db.Integer, primary_key=True)
    pipeline_id = db.Column(db.Integer, db.ForeignKey("workflow_pipelines.id"), nullable=False)

    # Cleanup configuration
    cleanup_patterns = db.Column(
        db.JSON
    )  # List of glob patterns to clean (e.g., ["temp/*", "artifacts/*.log"])
    retention_days = db.Column(db.Integer, default=7)  # Files older than this are deleted
    exclude_patterns = db.Column(db.JSON)  # Patterns to exclude from cleanup
    max_cleanup_size_mb = db.Column(db.Integer, default=100)  # Max size to clean in MB

    # Execution tracking
    files_cleaned = db.Column(db.Integer, default=0)
    space_freed_mb = db.Column(db.Float, default=0.0)
    cleanup_log = db.Column(db.JSON)  # Log of what was cleaned

    # Node identification (inherits from WorkflowNode)
    node_id = db.Column(db.String(50), nullable=False)
    label = db.Column(db.String(100), default="Cleanup")
    description = db.Column(db.Text, default="Clean up temporary files and artifacts")

    # Execution state
    status = db.Column(db.String(20), default="pending")
    started_at = db.Column(db.DateTime)
    completed_at = db.Column(db.DateTime)
    error_message = db.Column(db.Text)

    def execute_cleanup(self):
        """Execute the cleanup operation"""
        import glob
        import os
        from datetime import datetime, timedelta

        try:
            self.status = "running"
            self.started_at = datetime.utcnow()
            self.files_cleaned = 0
            self.space_freed_mb = 0.0
            self.cleanup_log = []

            cutoff_date = datetime.utcnow() - timedelta(days=self.retention_days)

            for pattern in self.cleanup_patterns or []:
                for file_path in glob.glob(pattern, recursive=True):
                    if self._should_exclude(file_path):
                        continue

                    try:
                        stat = os.stat(file_path)
                        file_date = datetime.fromtimestamp(stat.st_mtime)

                        if file_date < cutoff_date:
                            size_mb = stat.st_size / (1024 * 1024)
                            os.remove(file_path)

                            self.files_cleaned += 1
                            self.space_freed_mb += size_mb
                            self.cleanup_log.append(
                                {
                                    "file": file_path,
                                    "size_mb": size_mb,
                                    "deleted_at": datetime.utcnow().isoformat(),
                                }
                            )

                    except (OSError, FileNotFoundError) as e:
                        self.cleanup_log.append({"file": file_path, "error": str(e)})

            self.status = "completed"
            self.completed_at = datetime.utcnow()

        except Exception as e:
            self.status = "failed"
            self.error_message = str(e)
            self.completed_at = datetime.utcnow()

    def _should_exclude(self, file_path):
        """Check if file should be excluded from cleanup"""
        if not self.exclude_patterns:
            return False

        from fnmatch import fnmatch

        for pattern in self.exclude_patterns:
            if fnmatch(file_path, pattern):
                return True
        return False

    def __repr__(self):
        return f"<WorkflowCleanupNode {self.node_id}: cleaned {self.files_cleaned} files>"


class WorkflowEdge(db.Model):
    """
    Connections between nodes (control flow).
    Supports conditional routing for adaptive workflows.
    """

    __tablename__ = "workflow_edges"

    id = db.Column(db.Integer, primary_key=True)
    pipeline_id = db.Column(db.Integer, db.ForeignKey("workflow_pipelines.id"), nullable=False)

    # Edge definition
    source_node_id = db.Column(db.String(50), nullable=False)
    target_node_id = db.Column(db.String(50), nullable=False)

    # Conditional routing
    condition_type = db.Column(
        db.String(50), default="always"
    )  # always, on_success, on_failure, if_condition, budget_check
    condition_expression = db.Column(db.Text)  # Python expression or JSON logic

    # Edge metadata
    label = db.Column(db.String(100))  # For UI display
    priority = db.Column(db.Integer, default=0)  # For multiple edges from same source

    # Visual styling
    animated = db.Column(db.Boolean, default=False)
    style = db.Column(db.JSON)  # Custom styling for React Flow

    def __repr__(self):
        return f"<WorkflowEdge {self.source_node_id} -> {self.target_node_id}>"


class WorkflowTemplate(db.Model):
    """
    Pre-built workflow templates for common use cases.
    Example Corp-approved templates for best practices.
    """

    __tablename__ = "workflow_templates"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    category = db.Column(db.String(50))  # 'salesforce', 'sap', 'dynamics365', 'general', 'poc'

    # Template definition (full workflow graph)
    workflow_graph = db.Column(db.JSON, nullable=False)  # Includes nodes and edges
    default_config = db.Column(db.JSON)  # Default configuration for template

    # Template metadata
    is_official = db.Column(db.Boolean, default=False)  # Example Corp approved
    is_public = db.Column(db.Boolean, default=True)  # Visible to all users
    version = db.Column(db.String(20), default="1.0.0")

    # Usage tracking
    usage_count = db.Column(db.Integer, default=0)
    average_cost = db.Column(db.Float)  # Average cost per run
    average_duration_minutes = db.Column(db.Integer)
    success_rate = db.Column(db.Float)  # % of successful executions

    # Ratings and feedback
    average_rating = db.Column(db.Float)
    rating_count = db.Column(db.Integer, default=0)

    # Cost estimates
    estimated_cost_min = db.Column(db.Float)  # Min estimated cost
    estimated_cost_max = db.Column(db.Float)  # Max estimated cost

    # Requirements
    required_platform = db.Column(db.String(50))  # 'salesforce', 'sap', etc.
    required_capabilities = db.Column(db.JSON)  # Required BusinessCapability types

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    # Relationships
    created_by = db.relationship("User")
    instances = db.relationship(
        "WorkflowPipeline",
        backref="source_template",
        foreign_keys="WorkflowPipeline.template_id",
        overlaps="template",
    )

    def __repr__(self):
        return f"<WorkflowTemplate {self.id}: {self.name}>"


class WorkflowExecution(db.Model):
    """
    Execution history for workflow pipelines.
    Tracks each run with full state for debugging and analytics.
    """

    __tablename__ = "workflow_executions"

    id = db.Column(db.Integer, primary_key=True)
    pipeline_id = db.Column(db.Integer, db.ForeignKey("workflow_pipelines.id"), nullable=False)

    # Execution metadata
    execution_number = db.Column(db.Integer)  # Sequential execution number for this pipeline
    status = db.Column(db.String(20))  # completed, failed, cancelled, timeout

    # State snapshot
    workflow_state_start = db.Column(db.JSON)  # State at start
    workflow_state_end = db.Column(db.JSON)  # State at end

    # Metrics
    started_at = db.Column(db.DateTime, nullable=False)
    completed_at = db.Column(db.DateTime)
    duration_seconds = db.Column(db.Integer)
    cost_total = db.Column(db.Float, default=0.0)

    # Node execution summary
    nodes_executed = db.Column(db.Integer, default=0)
    nodes_succeeded = db.Column(db.Integer, default=0)
    nodes_failed = db.Column(db.Integer, default=0)
    nodes_skipped = db.Column(db.Integer, default=0)

    # Error tracking
    error_message = db.Column(db.Text)
    failed_node_id = db.Column(db.String(50))  # Which node failed

    # Trigger information
    triggered_by = db.Column(db.String(50))  # manual, webhook, scheduled, api
    triggered_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    # Relationships
    triggered_by_user = db.relationship("User")

    def __repr__(self):
        return (
            f"<WorkflowExecution {self.id}: Pipeline {self.pipeline_id} #{self.execution_number}>"
        )


class WorkflowNodeType(db.Model):
    """
    Registry of available node types for workflow builder.
    Defines node capabilities, configuration schema, and UI metadata.
    """

    __tablename__ = "workflow_node_types"

    id = db.Column(db.Integer, primary_key=True)
    node_type = db.Column(
        db.String(50), unique=True, nullable=False
    )  # e.g., "llm_architect", "validator"
    display_name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text)
    category = db.Column(db.String(50))  # input, ai, validation, platform, logic, output

    # Node capabilities
    is_ai_powered = db.Column(db.Boolean, default=False)
    supports_retry = db.Column(db.Boolean, default=True)
    requires_approval = db.Column(db.Boolean, default=False)

    # Configuration schema (JSON Schema)
    config_schema = db.Column(db.JSON)  # Defines configurable parameters

    # Cost estimation
    typical_cost = db.Column(db.Float)  # Typical cost per execution
    cost_unit = db.Column(db.String(20))  # 'per_call', 'per_token', 'fixed'

    # UI metadata
    icon = db.Column(db.String(50))  # Icon name for UI
    color = db.Column(db.String(20))  # Hex color for node

    # Implementation
    handler_class = db.Column(db.String(200))  # Python class that implements this node

    # Availability
    is_active = db.Column(db.Boolean, default=True)
    is_beta = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f"<WorkflowNodeType {self.node_type}>"


# =============================================================================
# EA WORKFLOW MODELS - Automated Enterprise Architecture Workflows
# =============================================================================


class EAWorkflowDefinition(db.Model):
    """
    Enterprise Architecture Workflow Definition.

    Defines reusable workflow templates for EA automation:
    - Application Onboarding
    - Gap Remediation
    - Vendor Selection
    - Compliance Scanning
    - Architecture Review
    """

    __tablename__ = "ea_workflow_definitions"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    # Phase A (Wave 4): nullable, backfilled later — do NOT add TenantMixin yet.
    organization_id = db.Column(db.Integer, db.ForeignKey("organizations.id"), nullable=True, index=True)

    # Workflow identity
    workflow_code = db.Column(db.String(50), unique=True, nullable=False, index=True)
    workflow_name = db.Column(db.String(200), nullable=False)
    workflow_description = db.Column(db.Text)

    # Classification
    workflow_category = db.Column(db.String(50), nullable=False, index=True)
    # application_management, vendor_management, gap_analysis, compliance, architecture
    workflow_type = db.Column(db.String(30), default="sequential")
    # sequential, parallel, conditional

    # Automation settings
    automation_level = db.Column(db.String(30), default="assisted")
    # full, assisted, hybrid, manual
    auto_approval_threshold = db.Column(db.Float, default=0.85)
    # Confidence threshold for auto-approval

    # Trigger configuration
    trigger_types = db.Column(db.JSON, default=["manual"])
    # ['manual', 'scheduled', 'event', 'api']

    # Step definitions (JSON array of step configs)
    steps = db.Column(db.JSON, nullable=False)

    # Notification settings
    notify_on_complete = db.Column(db.Boolean, default=True)
    notify_on_failure = db.Column(db.Boolean, default=True)

    # TOGAF ADM Phase mapping
    adm_phase = db.Column(db.String(20), nullable=True)
    # 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'prelim'
    adm_phase_name = db.Column(db.String(100), nullable=True)
    # 'Architecture Vision', 'Business Architecture', etc.

    # Phase gate contract — JSON list of required ArchiMate element types from prior phases
    # e.g. [{"phase": "A", "required_types": ["Driver", "Goal", "Stakeholder"]}]
    phase_gate_contract = db.Column(db.JSON, nullable=True)

    # Status
    is_active = db.Column(db.Boolean, default=True)

    # Execution statistics
    execution_count = db.Column(db.Integer, default=0)
    success_count = db.Column(db.Integer, default=0)
    last_executed_at = db.Column(db.DateTime)

    # Ownership
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    created_by = db.relationship("User", foreign_keys=[created_by_id])
    instances = db.relationship("EAWorkflowInstance", backref="definition", lazy="dynamic")
    schedules = db.relationship("EAWorkflowSchedule", backref="definition", lazy="dynamic")

    def to_dict(self):
        return {
            "id": self.id,
            "workflow_code": self.workflow_code,
            "workflow_name": self.workflow_name,
            "workflow_description": self.workflow_description,
            "workflow_category": self.workflow_category,
            "workflow_type": self.workflow_type,
            "automation_level": self.automation_level,
            "auto_approval_threshold": self.auto_approval_threshold,
            "trigger_types": self.trigger_types,
            "steps": self.steps,
            "notify_on_complete": self.notify_on_complete,
            "notify_on_failure": self.notify_on_failure,
            "adm_phase": self.adm_phase,
            "adm_phase_name": self.adm_phase_name,
            "is_active": self.is_active,
            "execution_count": self.execution_count,
            "success_count": self.success_count,
            "last_executed_at": self.last_executed_at.isoformat()
            if self.last_executed_at
            else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self):
        return f"<EAWorkflowDefinition {self.workflow_code}: {self.workflow_name}>"


class EAWorkflowInstance(db.Model):
    """
    Running or completed instance of an EA workflow.

    Tracks execution state, progress, and results.
    """

    __tablename__ = "ea_workflow_instances"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    # Phase A (Wave 4): nullable, backfilled later — do NOT add TenantMixin yet.
    organization_id = db.Column(db.Integer, db.ForeignKey("organizations.id"), nullable=True, index=True)

    # Instance identification
    instance_code = db.Column(db.String(100), unique=True, nullable=False)

    # Link to definition
    workflow_definition_id = db.Column(
        db.Integer, db.ForeignKey("ea_workflow_definitions.id"), nullable=False, index=True
    )

    # Execution state
    status = db.Column(db.String(30), default="pending", index=True)
    # pending, running, waiting_approval, completed, failed, cancelled

    # Context and data
    context = db.Column(db.JSON, default=dict)  # Input context and accumulated data
    current_step_index = db.Column(db.Integer, default=0)
    progress_percent = db.Column(db.Integer, default=0)

    # Approval tracking
    approval_requested_at = db.Column(db.DateTime)
    approved_items = db.Column(db.JSON)
    approved_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    approved_at = db.Column(db.DateTime)

    # Error tracking
    error_message = db.Column(db.Text)
    failed_step_id = db.Column(db.String(50))

    # Trigger information
    triggered_by = db.Column(db.String(30), default="manual")
    # manual, scheduled, event, api
    started_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    # Timing
    started_at = db.Column(db.DateTime)
    completed_at = db.Column(db.DateTime)
    duration_seconds = db.Column(db.Integer)

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Execution tracking
    total_steps = db.Column(db.Integer, default=0)
    completed_steps = db.Column(db.Integer, default=0)
    failed_steps = db.Column(db.Integer, default=0)
    current_step_id = db.Column(db.String(50))
    pending_approval_step_id = db.Column(db.String(50))
    error_step_id = db.Column(db.String(50))
    triggered_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    scheduled_at = db.Column(db.DateTime)

    # ADM iteration tracking (TOGAF iterative execution)
    iteration_number = db.Column(db.Integer, default=1, nullable=False, server_default="1")
    parent_iteration_id = db.Column(
        db.Integer, db.ForeignKey("ea_workflow_instances.id"), nullable=True
    )

    # Relationships
    started_by = db.relationship("User", foreign_keys=[started_by_id])
    approved_by = db.relationship("User", foreign_keys=[approved_by_id])
    parent_iteration = db.relationship(
        "EAWorkflowInstance", remote_side=[id], backref="child_iterations",
        foreign_keys=[parent_iteration_id]
    )
    step_executions = db.relationship(
        "EAWorkflowStepExecution", backref="instance", lazy="dynamic", cascade="all, delete-orphan"
    )

    def to_dict(self):
        defn = self.definition if self.definition is not None else None
        return {
            "id": self.id,
            "instance_code": self.instance_code,
            "workflow_definition_id": self.workflow_definition_id,
            "workflow_name": defn.workflow_name if defn else None,
            "workflow_code": defn.workflow_code if defn else None,
            "adm_phase": defn.adm_phase if defn else None,
            "adm_phase_name": defn.adm_phase_name if defn else None,
            "status": self.status,
            "context": self.context,
            "current_step_index": self.current_step_index,
            "progress_percent": self.progress_percent,
            "triggered_by": self.triggered_by,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "duration_seconds": self.duration_seconds,
            "error_message": self.error_message,
            "total_steps": self.total_steps,
            "completed_steps": self.completed_steps,
            "failed_steps": self.failed_steps,
            "current_step_id": self.current_step_id,
            "pending_approval_step_id": self.pending_approval_step_id,
            "scheduled_at": self.scheduled_at.isoformat() if self.scheduled_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<EAWorkflowInstance {self.instance_code}: {self.status}>"


class EAWorkflowStepExecution(db.Model):
    """
    Execution record for individual workflow steps.

    Tracks input, output, timing, and errors for each step.
    """

    __tablename__ = "ea_workflow_step_executions"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    # Phase A (Wave 4): nullable, backfilled later — do NOT add TenantMixin yet.
    organization_id = db.Column(db.Integer, db.ForeignKey("organizations.id"), nullable=True, index=True)

    # Link to instance
    instance_id = db.Column(
        db.Integer, db.ForeignKey("ea_workflow_instances.id"), nullable=False, index=True
    )

    # Step identification
    step_id = db.Column(db.String(50), nullable=False)
    step_name = db.Column(db.String(200))
    step_type = db.Column(db.String(30))  # automated, approval, notification

    # Execution state
    status = db.Column(db.String(30), default="pending")
    # pending, running, completed, failed, skipped

    # Data
    input_data = db.Column(db.JSON)
    output_data = db.Column(db.JSON)
    error_message = db.Column(db.Text)

    # Timing
    started_at = db.Column(db.DateTime)
    completed_at = db.Column(db.DateTime)
    duration_seconds = db.Column(db.Integer)

    # Retry tracking
    retry_count = db.Column(db.Integer, default=0)
    max_retries = db.Column(db.Integer, default=3)

    # Step index and service dispatch
    step_index = db.Column(db.Integer, default=0)
    service_class = db.Column(db.String(200))
    service_method = db.Column(db.String(100))
    # Approval tracking
    requires_approval = db.Column(db.Boolean, default=False)
    approval_status = db.Column(db.String(30))
    approved_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    approved_at = db.Column(db.DateTime)
    error_traceback = db.Column(db.Text)

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Relationships
    approved_by = db.relationship("User", foreign_keys=[approved_by_id])

    def to_dict(self):
        return {
            "id": self.id,
            "instance_id": self.instance_id,
            "step_id": self.step_id,
            "step_name": self.step_name,
            "step_type": self.step_type,
            "step_index": self.step_index if self.step_index is not None else 0,
            "status": self.status,
            "input_data": self.input_data,
            "output_data": self.output_data,
            "error_message": self.error_message,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "duration_seconds": self.duration_seconds,
            "retry_count": self.retry_count,
            "approval_status": self.approval_status,
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
        }

    def __repr__(self):
        return f"<EAWorkflowStepExecution {self.step_id}: {self.status}>"


class EAWorkflowSchedule(db.Model):
    """
    Schedule configuration for automated workflow execution.

    Supports daily, weekly, monthly, and cron-based scheduling.
    """

    __tablename__ = "ea_workflow_schedules"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    # Phase A (Wave 4): nullable, backfilled later — do NOT add TenantMixin yet.
    organization_id = db.Column(db.Integer, db.ForeignKey("organizations.id"), nullable=True, index=True)

    # Link to definition
    workflow_definition_id = db.Column(
        db.Integer, db.ForeignKey("ea_workflow_definitions.id"), nullable=False, index=True
    )

    # Schedule identification
    schedule_name = db.Column(db.String(200), nullable=False)

    # Schedule configuration
    schedule_type = db.Column(db.String(30), nullable=False)
    # daily, weekly, monthly, cron

    cron_expression = db.Column(db.String(100))
    time_of_day = db.Column(db.Time)
    day_of_week = db.Column(db.Integer)  # 0=Monday, 6=Sunday
    day_of_month = db.Column(db.Integer)  # 1 - 31
    timezone = db.Column(db.String(50), default="UTC")

    # Default context for scheduled runs
    default_context = db.Column(db.JSON, default=dict)

    # Status
    is_active = db.Column(db.Boolean, default=True)

    # Execution tracking
    last_run_at = db.Column(db.DateTime)
    next_run_at = db.Column(db.DateTime)
    run_count = db.Column(db.Integer, default=0)
    failure_count = db.Column(db.Integer, default=0)

    # Ownership
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    created_by = db.relationship("User")

    def to_dict(self):
        return {
            "id": self.id,
            "workflow_definition_id": self.workflow_definition_id,
            "schedule_name": self.schedule_name,
            "schedule_type": self.schedule_type,
            "cron_expression": self.cron_expression,
            "time_of_day": self.time_of_day.isoformat() if self.time_of_day else None,
            "day_of_week": self.day_of_week,
            "day_of_month": self.day_of_month,
            "timezone": self.timezone,
            "is_active": self.is_active,
            "last_run_at": self.last_run_at.isoformat() if self.last_run_at else None,
            "next_run_at": self.next_run_at.isoformat() if self.next_run_at else None,
            "run_count": self.run_count,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<EAWorkflowSchedule {self.schedule_name}: {self.schedule_type}>"


# ============================================================================
# State Machine Enforcement via SQLAlchemy Events
# ============================================================================


def _validate_workflow_status(target, value, oldvalue, initiator):
    """SQLAlchemy event listener that validates EAWorkflowInstance status transitions."""
    if oldvalue is value or oldvalue is None:
        return value
    if oldvalue is attributes.NO_VALUE or oldvalue is attributes.NEVER_SET:
        return value
    if oldvalue == value:
        return value
    allowed = _WORKFLOW_TRANSITIONS.get(oldvalue, set())
    if value not in allowed:
        _state_logger.warning(
            "Invalid EAWorkflowInstance transition blocked: %s -> %s (allowed: %s)",
            oldvalue, value, allowed or "none (terminal)",
        )
        raise ValueError(
            f"Invalid EAWorkflowInstance status transition: {oldvalue} -> {value}. "
            f"Allowed: {allowed or 'none (terminal state)'}"
        )
    _state_logger.debug("EAWorkflowInstance status: %s -> %s", oldvalue, value)
    return value


event.listen(EAWorkflowInstance.status, "set", _validate_workflow_status, retval=True)


class EAWorkflowNotification(db.Model):
    """
    Notification record for EA workflow events.
    Persists every notification for audit trail and in-app display.
    """
    __tablename__ = "ea_workflow_notifications"
    __table_args__ = {"extend_existing": True}

    id = db.Column(db.Integer, primary_key=True)
    # Phase A (Wave 4): nullable, backfilled later — do NOT add TenantMixin yet.
    organization_id = db.Column(db.Integer, db.ForeignKey("organizations.id"), nullable=True, index=True)
    workflow_instance_id = db.Column(db.Integer, db.ForeignKey("ea_workflow_instances.id"), nullable=False, index=True)
    recipient_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    template = db.Column(db.String(100))
    subject = db.Column(db.String(500))
    body = db.Column(db.Text)
    channel = db.Column(db.String(30), default="in_app")  # in_app, email

    is_read = db.Column(db.Boolean, default=False)
    sent_at = db.Column(db.DateTime, default=datetime.utcnow)
    read_at = db.Column(db.DateTime)

    # Delivery status
    delivery_status = db.Column(db.String(30), default="sent")  # sent, failed, queued
    delivery_error = db.Column(db.Text)

    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # Relationships
    instance = db.relationship("EAWorkflowInstance", backref=db.backref("notifications", lazy="dynamic"))
    recipient = db.relationship("User")

    def to_dict(self):
        return {
            "id": self.id,
            "workflow_instance_id": self.workflow_instance_id,
            "template": self.template,
            "subject": self.subject,
            "channel": self.channel,
            "is_read": self.is_read,
            "sent_at": self.sent_at.isoformat() if self.sent_at else None,
            "delivery_status": self.delivery_status,
        }

    def __repr__(self):
        return f"<EAWorkflowNotification {self.id}: {self.template} → user {self.recipient_id}>"


class WorkflowRunWatcher(db.Model):
    """Users watching a specific workflow run for in-app notifications."""
    __tablename__ = "workflow_run_watchers"
    __table_args__ = (
        db.UniqueConstraint("workflow_instance_id", "user_id", name="uq_watcher_instance_user"),
        {"extend_existing": True},
    )

    id = db.Column(db.Integer, primary_key=True)
    workflow_instance_id = db.Column(
        db.Integer, db.ForeignKey("ea_workflow_instances.id"), nullable=False, index=True
    )
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    instance = db.relationship("EAWorkflowInstance", backref=db.backref("watchers", lazy="dynamic"))
    user = db.relationship("User")
